// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfm41-R_Sj-upIJx3wB6GqC-FY4yr5kg',
    appId: '1:301185503022:web:21f2ed8f19b171ac8df4bf',
    messagingSenderId: '301185503022',
    projectId: 'learnsphere-9987f',
    authDomain: 'learnsphere-9987f.firebaseapp.com',
    storageBucket: 'learnsphere-9987f.firebasestorage.app',
    measurementId: 'G-PJ8V3DN0W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwwRVxpoIjv_oDZIcca2jTa2GGFikon8',
    appId: '1:301185503022:android:5bafa6f0b20bbcc18df4bf',
    messagingSenderId: '301185503022',
    projectId: 'learnsphere-9987f',
    storageBucket: 'learnsphere-9987f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJl7ajtgSVpjqGGLg3f3JEh9mTWryhVSQ',
    appId: '1:301185503022:ios:2fd508f2821a00d48df4bf',
    messagingSenderId: '301185503022',
    projectId: 'learnsphere-9987f',
    storageBucket: 'learnsphere-9987f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJl7ajtgSVpjqGGLg3f3JEh9mTWryhVSQ',
    appId: '1:301185503022:ios:2fd508f2821a00d48df4bf',
    messagingSenderId: '301185503022',
    projectId: 'learnsphere-9987f',
    storageBucket: 'learnsphere-9987f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfm41-R_Sj-upIJx3wB6GqC-FY4yr5kg',
    appId: '1:301185503022:web:e14e7cc7029530ff8df4bf',
    messagingSenderId: '301185503022',
    projectId: 'learnsphere-9987f',
    authDomain: 'learnsphere-9987f.firebaseapp.com',
    storageBucket: 'learnsphere-9987f.firebasestorage.app',
    measurementId: 'G-6JQ9S8XYLS',
  );
}
