name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  http: ^1.3.0
  url_launcher: ^6.1.7
  fl_chart: ^0.70.2
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  file_picker: ^9.0.0
  timeline_tile: ^2.0.0
  font_awesome_flutter: ^10.8.0
  flutter_3d_controller: ^2.1.0
  graphview: ^1.2.0
  crypto: ^3.0.6
  shimmer: ^3.0.0
  percent_indicator: ^4.2.4
  animated_text_kit: ^4.2.3
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.12.1
  uni_links: ^0.5.1
  share_plus: ^10.1.4
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  # fl_chart: ^0.62.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets\HomeImg.png
    - Assets\learnsphere.png
    - Assets\Rectangle.png
    - Assets\blackbg.webp
    - Assets/roadmap_output.json
  #   - images/a_dot_ham.jpeg
